[project]
name = "Pulse Music"
version = "0.2.4"
dependencies = [
    "flet==0.28.3",
    "requests==2.32.5",
    "deep-translator==1.11.4",
    "python-dotenv==1.1.1",
    "lyricsgenius==3.7.2",
    "langdetect==1.0.9",
    "aiohttp==3.12.15",
    "mutagen==1.47.0",
    "google-auth-oauthlib==1.2.2",
    "aiofiles==25.1.0",
    "pyglet==2.1.15",
    "pywhatkit==5.4"
]

[tool.flet]
org = "com.barbozasoftware"
product = "Pulse Music"
company = "Barboza Software"
copyright = "Copyright (C) 2026"

[tool.flet.app]
path = "."

[tool.flet.app.windows]
data = [
    "assets/app/audio_main.exe",
    "assets/app/information_main.exe"
]